version: "3.9"

services:
  backend:
    build:
      context: .
    ports:
      - "3012:3012"
    volumes:
      - .:/app # Monta todo el proyecto para facilitar el desarrollo
      - /app/node_modules # Evita conflictos con los node_modules locales
      - ./public:/app/public # Monta la carpeta public como un volumen
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://root:example@mongo:27017/?directConnection=true
    env_file:
      - .env.development # Carga las variables desde este archivo
    depends_on:
      - mongo
    tty: true

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
