version: "3.9"

services:
  backend:
    build:
      context: .
    ports:
      - "3012:3012"
    volumes:
      - .:/app
      - /app/node_modules
      - ./public:/app/public
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://root:example@mongo:27017/?directConnection=true
      - COUCHDB_URI=http://admin:password@couchdb:5984

    env_file:
      - .env.development
    depends_on:
      - couchdb
    tty: true

  couchdb:
    image: couchdb:3.3
    container_name: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    # Montamos un volumen para que los datos de CouchDB persistan
    volumes:
      - couchdb_data:/opt/couchdb/data
    restart: always

volumes:
  # mongodb_data:
  couchdb_data:
