name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Railway
  # You may pin to the exact commit or the version.
  # uses: jzeuzs/action-railway@b7bad8e07bcb36d2a21f90f2ee6b2510125a6948
        uses: jzeuzs/action-railway@v1.1.4
        with:
    # The Railway Token
         railway_token: ${{ secrets.RAILWAY_API_TOKEN }}
          

      - name: Log in to Railway
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: |
          echo "${{ secrets.RAILWAY_API_TOKEN }}" | railway login

      - name: Build and push Docker image
        run: |
          docker build -t server-atekos .
          docker tag server-atekos registry.railway.app/server-atekos:latest
          docker push registry.railway.app/server-atekos:latest

      - name: Deploy to Railway
        run: |
          railway up --detach
